WEB/Models/Login/MenuViewModel.cs
using System.Collections.Generic;

namespace WEB.Models.Login
{

    /// <summary>
    /// 菜单视图模式
    /// </summary>
    public class MenuViewModel
    {
        public MenuViewModel()
        {
            Children= new List<MenuViewModel>();
        }
        public string Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 链接地址
        /// </summary>
        public string Href { get; set; }
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { get; set; }
        /// <summary>
        /// 子菜单
        /// </summary>
        public List<MenuViewModel> Children { get; set; }
    }
}

WEB/Controllers/LoginController.cs
/************聚米支付平台__业务逻辑************/
//描述：处理登录等业务逻辑
//功能：处理登录等业务逻辑
//开发者：谭玉科
//开发时间: 2016.03.14
/************聚米支付平台__业务逻辑************/
using JMP.BLL;
using JMP.TOOL;
using System;
using System.Configuration;
using System.Data;
using System.Web;
using System.Web.Mvc;
using WEB.Util.Logger;

namespace WEB.Controllers
{
    /// <summary>
    /// 类名：LoginController
    /// 功能：
    /// 详细：
    /// 修改日期：2016.03.14
    /// </summary>
    public class LoginController : Controller
    {
        private static readonly ILogWriter Logger = LogWriterManager.GetOperateLogger;
        #region 登录逻辑
        /// <summary>
        /// 登录页面
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 用户登录
        /// </summary>
        /// <param name="action">操作类型</param>
        /// <param name="userName">登录名</param>
        /// <param name="userPwd">用户密码</param>
        /// <param name="valCode">验证码</param>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = false)]
        public JsonResult UserLogin(string action, string userName, string userPwd, string valCode)
        {
            object result = new { mag = "操作失败！", status = "0" };
            if (action != "login") return Json(result);
            var isDebug = ConfigurationManager.AppSettings["IsDebug"];
            if (!string.IsNullOrEmpty(isDebug) && isDebug == "true")
            {
                result = DoLogin(userName, userPwd);
                return Json(result);
            }

            result = string.Equals(valCode, Session["ValidateCode"].ToString(), StringComparison.CurrentCultureIgnoreCase) ? DoLogin(userName, userPwd) : new { mag = "验证码错误！", status = "3" };
            return Json(result);
        }

        private object DoLogin(string userName, string userPwd)
        {
            object result;
            var bllLimit = new jmp_limit();
            var bll = new jmp_locuser();
            var model = bll.GetModel(userName);
            //加密用户登录密码
            var jmPwd = DESEncrypt.Encrypt(userPwd).ToLower();
            if (model != null)
            {
                if (model.u_loginname == userName && model.u_pwd.ToLower() == jmPwd)
                {
                    UserInfo.UserId = model.u_id;
                    UserInfo.UserName = model.u_realname;
                    UserInfo.UserNo = model.u_loginname;
                    UserInfo.UserRoleId = model.u_role_id;
                    UserInfo.UserDept = model.u_department;
                    UserInfo.UserPostion = model.u_position;
                    var dtLimit = bllLimit.GetUserLimitSession(model.u_id, model.u_role_id);
                    if (dtLimit.Rows.Count > 0)
                    {
                        Session["dtSession"] = dtLimit;
                        model.u_count += 1;
                        bll.Update(model);
                        var log = string.Format("用户({0})于{1}登录后台系统。", UserInfo.UserName, DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
                        AddLocLog.AddLog(UserInfo.UserId, 2, RequestHelper.GetClientIp(), "用户" + UserInfo.UserName + "登录。", log);
                        result = new { mag = "登录成功！", status = "1" };
                    }
                    else
                    {
                        result = new { mag = "权限不足！", status = "4" };
                    }

                }
                else
                    result = new { mag = "用户名或密码错误！", status = "2" };
            }
            else
                result = new { mag = "用户名或密码错误！", status = "2" };
            return result;
        }

        /// <summary>
        /// 获取验证码
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult GetValidateCode()
        {
            ValidateCode vCode = new ValidateCode();
            string code = vCode.GetRandomCode(4);
            Session["ValidateCode"] = code;
            byte[] bytes = vCode.CreateValidateGraphic(code);
            return File(bytes, @"image/jpeg");
        }
        #endregion
        #region 首页框架
        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = true, IsRole = false)]
        public ActionResult Default()
        {
            string top_menu = string.Empty;
            string son_menu = string.Empty;

            int u_id = UserInfo.Uid;
            int r_id = UserInfo.Uid;
            top_menu = GetTopMenu(u_id, r_id, ref son_menu);
            string user_name = UserInfo.UserName;

            ViewBag.TopMenu = new HtmlString(top_menu);
            ViewBag.SonMenu = new HtmlString(son_menu);
            ViewBag.UserName = user_name;

            return View();
        }

        /// <summary>
        /// 查询最近五分钟订单数量
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = true, IsRole = false)]
        public string SelectOrderList()
        {
            string str = "";
            JMP.BLL.jmp_order bll = new jmp_order();
            // string TableName = "jmp_order";
            string TableName = "jmp_order_" + (JMP.TOOL.WeekDateTime.GetWeekFirstDayMon(DateTime.Now)).ToString("yyyyMMdd");
            // 5分钟无新订单产生
            int ordernum = Convert.ToInt32(bll.GetOrderNum(DateTime.Now, TableName));
            //5分钟成功的订单
            int SuccessNum = Convert.ToInt32(bll.SelectCG(DateTime.Now, TableName));
            //if (ordernum < 1)
            //{
            //    TableName = "jmp_order_" + (JMP.TOOL.WeekDateTime.GetWeekFirstDayMon(DateTime.Now).AddDays(-7)).ToString("yyyyMMdd");
            //    ordernum = Convert.ToInt32(bll.GetOrderNum(DateTime.Now, TableName));
            //}
            //if (SuccessNum < 1)
            //{
            //    TableName = "jmp_order_" + (JMP.TOOL.WeekDateTime.GetWeekFirstDayMon(DateTime.Now).AddDays(-7)).ToString("yyyyMMdd");
            //    SuccessNum = Convert.ToInt32(bll.SelectCG(DateTime.Now, TableName));
            //}
            str = SuccessNum.ToString() + " /" + ordernum.ToString();
            return str;
        }
        /// <summary>
        /// 获取订单最后一次支付成功的时间
        /// </summary>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = true, IsRole = false)]
        public string SelectOrderTimes()
        {
            string str = "";
            JMP.BLL.jmp_order bll = new jmp_order();
            string TableName = "jmp_order";
            string times = "";
            //if (bll.SelectCgTimes(TableName) == null)
            //{
            //    TableName = "jmp_order_" + (JMP.TOOL.WeekDateTime.GetWeekFirstDayMon(DateTime.Now).AddDays(-7)).ToString("yyyyMMdd");
            //    times = bll.SelectCgTimes(TableName) == null ? "" : bll.SelectCgTimes(TableName).ToString();
            //}
            //else
            //{
            times = bll.SelectCgTimes(TableName) == null ? "" : bll.SelectCgTimes(TableName).ToString();
            // }
            str = string.IsNullOrEmpty(times) ? "无数据" : DateTime.Parse(times).ToString("yyyy-MM-dd HH:mm:ss");
            return str;
        }
        /// <summary>
        /// 获取顶级菜单
        /// </summary>
        /// <param name="uId">用户id</param>
        /// <param name="rId">权限id</param>
        /// <param name="son_menu">子级菜单</param>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = true, IsRole = false)]
        private string GetTopMenu(int uId, int rId, ref string son_menu)
        {
            //顶级菜单
            string topMenu = string.Empty;
            son_menu = "<ul><li id=\"menu_0\" class=\"\"><a href=\"javascript:\" onclick=\"TabObj(this, '交易走势图', '/REPORT/Index');\" ><span>交易走势图</span></a></li></ul>";
            jmp_limit bll = new jmp_limit();
            DataTable dt = bll.GetUserLimit(uId, rId, 0);
            string temp = "<li class=\"header-body-nav-li{0}\"><a href=\"javascript:\" {1}>{2}</a></li>";
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                DataRow dr = dt.Rows[i];
                string licss = i == 0 ? " selected" : "";
                string acss = !string.IsNullOrEmpty(dr["l_icon"].ToString()) ? "class=\"icon " + dr["l_icon"].ToString() + "\"" : "";
                string lname = !string.IsNullOrEmpty(dr["l_name"].ToString()) ? dr["l_name"].ToString() : "";
                topMenu += string.Format(temp, licss, acss, lname);
                int tid = int.Parse(dr["l_id"].ToString());
                son_menu += "<ul style=\"display:none\">" + GetSonMenu(uId, rId, tid) + "</ul>";
            }
            return topMenu;
        }

        /// <summary>
        /// 获取子级菜单
        /// </summary>
        /// <param name="uId">用户id</param>
        /// <param name="rId">权限id</param>
        /// <param name="topId">父级id</param>
        /// <returns></returns>
        [LoginCheckFilterAttribute(IsCheck = true, IsRole = false)]
        private string GetSonMenu(int uId, int rId, int topId)
        {
            string son_menu = string.Empty;
            jmp_limit bll = new jmp_limit();
            DataTable dt = bll.GetUserLimit(uId, rId, topId);
            string temp = "<li id=\"{0}\" {1}><a id=\"{2}\" href=\"javascript:\" onclick=\"TabObj(this,'{4}','{3}')\"><span>{4}</span></a></li>";
            string action = Request["action"];
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                DataRow dr = dt.Rows[i];
                string lid = !string.IsNullOrEmpty(dr["l_id"].ToString()) ? "menu_" + dr["l_id"].ToString() : "menu_" + i + 1;
                string aid = !string.IsNullOrEmpty(dr["l_id"].ToString()) ? "menu_" + dr["l_id"].ToString() + "_a" : "menu_" + i + 1 + "_a";
                string css = i == 0 ? "class=\"selected\"" : "";

WEB/Controllers/PartialController.cs
using System.Linq;
using System.Web.Mvc;
using JMP.TOOL;
using WEB.Util;

namespace WEB.Controllers
{
    public class PartialController : Controller
    {
        public ActionResult Menu()
        {
            var uId = UserInfo.Uid;
            var rId = UserInfo.UserRid;
            var menuLoader = new MenuLoader();
            var model = menuLoader.Load(uId, rId).ToList();
            return PartialView("_Menu",model);
        }
        public ActionResult MenuMobile()
        {
            var uId = UserInfo.Uid;
            var rId = UserInfo.UserRid;
            var menuLoader = new MenuLoader();
            var model = menuLoader.Load(uId, rId).ToList();
            return PartialView("_Menu_Mobile", model);
        }
    }
}

WEB/Views/Login/Default.cshtml
@{
    ViewBag.Title = "仪表盘";
    Layout = null;
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>盾行平台管理系统</title>
    <!-- css -->
    @JMP.TOOL.UserHelper.css("/plugin/font-awesome/css/font-awesome.min.css")
    <link href="~/assets/bootstrap.3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    @JMP.TOOL.UserHelper.css("base.css")
    @JMP.TOOL.UserHelper.css("main.css")
    @JMP.TOOL.UserHelper.css("theme.css")
    @JMP.TOOL.UserHelper.js("jquery-1.12.4.min.js")
    <script src="~/assets/bootstrap.3.3.7/js/bootstrap.min.js"></script>
    @JMP.TOOL.UserHelper.js("layout.js")
    @JMP.TOOL.UserHelper.js("JValidator.js")
    @JMP.TOOL.UserHelper.js("layer/layer.js")
    @JMP.TOOL.UserHelper.js("PubMethod.js")
</head>
<body>
    <header class="header-wrapper clearfix">
        <a href="javascript:void(0);" class="header-brand" title="logo">
            <img src="../images/head_logo.png" alt="logo" class="logo-white">
        </a>
        <div class="header-nav clearfix">
            <!---->
            <a class="head-btn btn-bars">
                <i class="fa fa-bars"></i>
            </a>
            <ul class="header-pull clearfix">
                <li>
                    <a href="javascript:" class="txt">最近五分钟成交：<span id="OrderNum" class="num"></span>  成功/订单数</a>
                    <a href="javascript:" class="txt">最后一笔订单交易时间：<span id="TimeOrder" class="num"></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)" class="head-btn top-btn cnt head-btn-user">
                        <span class="name">@ViewBag.UserName <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a id="tcClick">修改密码</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a id="nav-right-exit" class="head-btn cnt">
                        <i class="fa fa-power-off"></i>
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!--顶部 end-->
    <div class="">
        <div class="idx-fl">
            <div class="navbar-collapse">
                @{
                    try
                    {
                        Html.RenderAction("Menu", "Partial");
                    }
                    catch
                    {
                    }
                }
            </div>
            <div class="idx-fl-bg"></div>
        </div>
        <div class="cont-wrapper">
            <div class="cont-wrapper-pren">
                <div class="cont-wrapper-min">
                    <div class="tab-dvrep">
                        <i class="fa fa-caret-left faicon" id="fa-caret-left"></i>
                        <i class="fa fa-caret-right faicon" id="fa-caret-right"></i>
                        <div id="btn_tab_close_action" class="btn-group" role="group">
                            <button id="btnGroupVerticalDrop2" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 页签操作 <span class="caret"></span> </button>
                            <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop2">
                                <li><a onclick="closeCurrentTab();">关闭当前页</a></li>
                                <li><a onclick="closeAllTabs();">全部关闭</a></li>
                                <li><a onclick="closeOtherTabs();">除此之外全部关闭</a></li>
                            </ul>
                        </div>
                        <div class="tab-items-container">
                            <ul id="tab-panel-menu-list" class="tab-panel">
                                <li data-id="tab_home" data-closable="false" class="active">
                                    <span onclick="tabmenu(this)">首页</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div id="tab-panel-content-wrapper" class="tab-panel-content">
                        <div data-id="tab_home" class="cont active">
                            <iframe src="/report/index"></iframe>
                        </div>
                    </div>
                </div>
                @*<div class="cont-wrapper-min">
                        <ul id="tab-panel-menu-list" class="tab-panel">

                        </ul>
                        <div id="tab-panel-content-wrapper" class="tab-panel-content"></div>
                    </div>*@
            </div>
            <footer class="footer-bar">
                Copyright ©2013-2020 AdJuMi.com All Rights Reserved.&nbsp;&nbsp;&nbsp;&nbsp;盾行支付平台 版权所有 ICP备13013448号-2
            </footer>
        </div>
    </div>
    <script src="~/js/com.js"></script>
    <script src="~/js/index.js"></script>
    <script>
        $(function () {
            //退出
            $("#nav-right-exit").unbind("click").click(function () {
                layer.confirm('您确定要退出吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function () {
                    $.post("/Login/LoginOut", { action: "exit" }, function (data) {
                        if (data.success) {
                            window.top.location.href = data.gourl;
                        }
                    });
                });

            });
            $("#tcClick").click(function () {
                window.parent.ShouwDiaLogWan("修改密码", 650, 350, "/Login/UpdatePwd");
            })

            //首页
            $("#nav-right-index").unbind("click").click(function () {
                $("#section-nav").find("ul").hide().eq(0).show().find("li").eq(0).find("a").click();

            });
            OrderCount();
            //时钟效果
            //setInterval("GetDate()", 1000);
            setInterval("OrderCount()", 10000);

            /**/
            //tab选项卡-向左
            var prd = $(".tab-dvrep").innerWidth() - 175;//tab-ul父级宽度；
            var tab = $("#tab-panel-menu-list");//tab标题
            var tnswh = 0;
            var tnswhb = 0;
            $("#fa-caret-left").click(function () {
                var tns = 0;
                var bigb = tab.innerWidth() - prd;//滑动最大的像素
                var pageli = tab.find("li");
                if (tab.innerWidth() > prd) {
                    for (var i = 0; i < 3; i++) {
                        tns += $(pageli[i]).outerWidth();
                    }
                    if (tnswh == 0) {
                        tns = bigb - tns;
                    } else {
                        tns = tnswh - tns;
                    }
                    tnswh = tns;

                    var nums = parseInt(tab.css("transform").substr(20, 5));
                    if (tnswh < 64) {
                        tab.css("transition", "all 2s ease-out 0s");
                        tab.css("transform", "translate3d(0px, 0px, 0px)");
                        window.parent.ShowMsg("已经到第一页了！", "", "提示");
                        tnswh = 0;
                        return;
                    } else {
                        tab.css("transform", "translate3d(-" + tns + "px, 0px, 0px)");
                    }
                    //debugger;
                }
            });
            //tab选项卡-向右
            $("#fa-caret-right").click(function () {
                var tns = 0;
                var bigb = tab.innerWidth() - prd;//滑动最大的像素
                var pageli = tab.find("li");
                if (tab.innerWidth() > prd) {
                    for (var i = 0; i < 3; i++) {
                        tns += $(pageli[i]).outerWidth();
                    }
                    if (tnswhb == 0) {
                        tns = tns;
                    } else {
                        tns = tnswhb + tns;
                    }
                    tnswhb = tns;
                    if (tnswhb < bigb) {
                        tab.css("transition", "all 2s ease-out 0s");
                        tab.css("transform", "translate3d(-" + tns + "px, 0px, 0px)");
                    } else {
                        tab.css("transition", "all 2s ease-out 0s");
                        tab.css("transform", "translate3d(-" + (bigb - 1) + "px, 0px, 0px)");
                        tnswhb = 0;
                        window.parent.ShowMsg("已经到最后一页了！", "", "提示");
                        return;
                    }
                }
            });

        });


        //关闭当前选项卡
        function closeCurrentTab() {
            var currentTab = $("#tab-panel-menu-list").find("li.active");
            var closable = currentTab.attr("data-closable") === "true";
            //check current tab allow close
            if (!closable) {
                return false;
            }
            var prev = currentTab.prev();
            currentTab.remove();
            $("#tab-panel-content-wrapper").children("div.active").remove();
            //var lastTabIndex = $("#tab-panel-menu-list").length-1;

            
            var id = prev.attr("data-id");
            console.info(id);
            $("#tab-panel-menu-list li[data-id='"+id+"']").addClass("active");
            $("#tab-panel-content-wrapper div.cont[data-id='" + id + "']").addClass("active");

            return false;
        }

        //关闭所有选项卡
        function closeAllTabs() {
            $("#tab-panel-menu-list li[data-closable!='false']").each(function (i) {
                var target = $(this);
                var id = target.attr("data-id");
                target.remove();
                $("#tab-panel-content-wrapper div.cont[data-id='" + id + "']").remove();
            });

            $("#tab-panel-menu-list li:last").addClass("active");
            $("#tab-panel-content-wrapper div.cont:last").addClass("active");
            $("#tab-panel-menu-list").css("transform", "translate3d(0px, 0px, 0px)");
        }

        //关闭其他选项卡
        function closeOtherTabs() {
            $("#tab-panel-menu-list li[data-closable!='false']").each(function (i) {
                var target = $(this);
                var closable = target.attr("data-closable") === "true";
                var isActive = target.hasClass("active");
                //check current tab allow close
                if (closable && !isActive) {
                    var id = target.attr("data-id");
                    target.remove();
                    $("#tab-panel-content-wrapper div.cont[data-id='" + id + "']").remove();
                }
            });
            $("#tab-panel-menu-list").css("transform", "translate3d(0px, 0px, 0px)");
            //$("#tab-panel-menu-list li:last").addClass("active");
            //$("#tab-panel-content-wrapper div.cont:last").addClass("active");
        }

        function GetDate() {
            var today = new Date();
            var year = today.getFullYear();
            var month = today.getMonth() + 1;
            var day = today.getDate();
            var hours = today.getHours();
            var minutes = today.getMinutes();
            var seconds = today.getSeconds();
            //如果是单位数字，前面补0
            month = month < 10 ? "0" + month : month;
            day = day < 10 ? "0" + day : day;
            hours = hours < 10 ? "0" + hours : hours;
            hours = (hours <= 12 ? "上午" : "下午") + hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;
            //时间信息连成字符串
            var str = year + "年" + month + "月" + day + "日 " + hours + ":" + minutes + ":" + seconds;
            var obj = document.getElementById("header-head-time");
            obj.innerHTML = str;
        }
        function OrderCount() {
            $.post("/Login/SelectOrderList", function (order) {
                $("#OrderNum").html(order);
            })
            $.post("/Login/SelectOrderTimes", function (order) {
                $("#TimeOrder").html(order);
            })

        }

        //function scolls() {//滚动条
        //    $(".navbar-collapse").mCustomScrollbar();
        // }
    </script>
</body>
</html>

WEB/Views/Login/Default.mobile.cshtml
@{
    ViewBag.Title = "盾行平台管理系统[移动版]";
    Layout = "~/Views/UI/master.mobile.cshtml";
}
@JMP.TOOL.UserHelper.css("/plugin/font-awesome/css/font-awesome.min.css")
@JMP.TOOL.UserHelper.js("fusionchart/fusioncharts.js")
@JMP.TOOL.UserHelper.js("fusionchart/fusioncharts.theme.zune.js")
<div class="mobile-container">
    <div style="margin-bottom: 15px;display:none;">
        <p href="javascript:" class="txt">最近五分钟成交：<span id="OrderNum" class="num">加载中...</span>  成功/订单数</p>
        <p href="javascript:" class="txt">最后一笔订单交易时间：<span id="TimeOrder" class="num">加载中...</span></p>
    </div>
    <div class="plate-tab-ul-wrap">
        <h3 style="display:none;">24小时交易走势图</h3>
        <ul>
            <li><a id="date_0" class="selected" href="javascript:FusionChart(0)">今天(@ViewBag.moneycount/交易金额)</a></li>
            <li><a id="date_1" href="javascript:FusionChart(1)">昨天</a></li>
            <li><a id="date_2" href="javascript:FusionChart(2)">前天</a></li>
            <li><a id="date_3" href="javascript:FusionChart(3)">支付量走势图</a></li>
        </ul>
    </div>
    <div class="table-container table-responsive">
        <div id="chartObj" class="chart-main">
            <div id="chart"></div>
        </div>
    </div>
    <script type="text/javascript">
        function FusionChart(thatDay) {
            var winHeight = $(window).height() - 160;
            $.ajax({
                type: "post",
                contentType: "application/json; charset=utf-8",
                url: "/REPORT/DeviceTrend?days=" + thatDay,
                success: function (retJson) {
                    if (retJson === "0") {
                        var childHtm = '<div style="font-size:14px;color:#5e788a;font-weight:lighter;text-align:center;width:100%;">未查询到符合条件的数据</div>';
                        $("#chart").html(childHtm);
                    } else {
                        var data = eval('(' + retJson + ')');
                        var chart = new FusionCharts({
                            type: "msline",
                            renderAt: "chart",
                            width: "100%",
                            height: winHeight + "px",
                            dataSource: data,
                            dataFormat: "json"
                        }).render();
                    }
                }
            });
            //移除所有的样式
            $("#date_0").removeClass("selected");
            $("#date_1").removeClass("selected");
            $("#date_2").removeClass("selected");
            $("#date_3").removeClass("selected");
            //为当前选中添加样式
            if (thatDay === 0) {
                $("#date_0").addClass("selected");
            }
            else if (thatDay === 1) {
                $("#date_1").addClass("selected");
            }
            else if (thatDay === 2) {
                $("#date_2").addClass("selected");
            }
            else if (thatDay === 3) {
                $("#date_3").addClass("selected");
            }
        }

        function OrderCount() {
            $.post("/Login/SelectOrderList",
                function (order) {
                    $("#OrderNum").html(order);
                });
            $.post("/Login/SelectOrderTimes",
                function (order) {
                    $("#TimeOrder").html(order);
                });

        }

        $(window).resize(function () {
            mainHeightAuto();
        });

        $(function () {
            mainHeightAuto();
            FusionChart(0);
            OrderCount();
            setInterval("OrderCount()", 10000);
        });
    </script>
</div>